sendprog is built with GCC; use the GCC with your Linux system, or download gcc for Cygwin or MinGW
on a Windows machine.

Build with:
gcc -o sendprog sendprog.c

Other C compilers would probably also work.
